version: '3.8'
services:
        jenkins-server:
                image: jenkins/jenkins
                ports:
                        - "8080:8080"
                        - "5000:5000"
                volumes:
                        - jenkins:/var/jenkins_home
                        - /var/run/docker.sock:/var/run/docker.sock
                networks:
                        net:
                                ipv4_address: 10.4.0.9
        
        bitbucket-server:
                image: atlassian/bitbucket-server
                ports:
                        - "7990:7990"
                        - "7999:7999"
                environment:
                        - BITBUCKET_HOME=/var/atlassian/application-data/bitbucket/
                volumes:
                        - bitbucket:/var/atlassian/application-data/bitbucket
                networks:
                        net:
                                ipv4_address: 10.4.0.10
                                
        postgresdb:
                image: postgres
                environment:
                        POSTGRES_USER_FILE: /run/secrets/db_user
                        POSTGRES_PASSWORD_FILE: /run/secrets/db_password
                        POSTGRES_DB: Bitbucket
                secrets:
                        - db_user
                        - db_password
                volumes:
                        - postgres:/var/lib/postgresql/data
                networks:
                        net:
                                ipv4_address: 10.4.0.11

volumes:
        jenkins:
        bitbucket:
        postgres:

secrets:
        db_user:
                external: true
        db_password:
                external: true

networks:
        net:
                ipam:
                        driver: default
                        config: 
                                - subnet: 10.4.0.0/16
